### ISSUE TITLE
ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null, message=null}

### ISSUE THREAD

**Issue by pdavid0** [googlesamples/android-nearby#14]
Implemented this sample on mobile & tablet everything is perfect ! But whit Android TV ADT-1 v5.0.2 build LRX22G these eloquent message shows up.

```
GmsClient: unable to connect to service: com.google.android.gms.nearby.messages.service.NearbyMessagesService.START
```

```
D/NearbyMessagesClient: Failed to emit client lifecycle event ACTIVITY_STOPPED due to GmsClient being disconnected
```

```
NearbyMessagesClient: Failed to emit client lifecycle event CLIENT_DISCONNECTED due to GmsClient being disconnected
```

The callback :

```
@Override public void onConnectionFailed(@NonNull ConnectionResult connectionResult) 
```

Output :

```
ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null, message=null}
```

Like I said, everything works in the mobile module. I doubled checked API_KEY, gradle dependencies, Manifest meta, nope, I even created a listing for the APK and created a Game on Google Play Console, nothing.

Any ideas ? Thanks !

**Comment by pelotasplus** [comment]
Have same problem on Sony KDL-55W75xC Android TV. In short, there is no `NearbyMessagesService` available in `com.google.android.gms` package on my TV.

More info here http://stackoverflow.com/a/36694016/1018109

**Comment by brianduff** [comment]
Nearby Messages is not supported on Android TV.
