### ISSUE TITLE
Stale Nearby Notifications?

### ISSUE THREAD

**Issue by nboppuri** [googlesamples/android-nearby#31]
I had a Beacon registered to Google Nearby and then created a new notification. I got this notifications just fine on my LG G4 Android phone. Later, I deleted the old notification and created a newer notification for the same beacon. However, I still keep getting the same old notification (that doesn't exist anymore for the beacon) in addition to the new notification. I verified this again and again on the Google Beacon Dashboard that the old notification does not exist for the beacon. I tried this with a third new notification (after deleting the others) and I now see all 3 notifications showing up. Where is this stale data coming from even though I see no evidence of the old notification's existence in the Beacon dashboard for the Beacon? Is this a known bug in Google Nearby Notifications?

**Comment by YorkshireVets** [comment]
Hi,
I am having the same problem. Have you had any luck resolving it yet? Also, which beacons are you using? I have a Sensoro USB, and was wondering if this was a google beacon dashboard issue, or a Sensoro one.

**Comment by nboppuri** [comment]
http://stackoverflow.com/questions/38881772/stale-google-nearby-notifications

**Comment by YorkshireVets** [comment]
Thanks.
