### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by s1mar** [googlesamples/android-nearby#37]
Is it possible to transmit images? since the Connections.MAX_RELIABLE_MESSAGE_LEN is just about 4 KB's

**Comment by samtstern** [comment]
It's possible to transmit images but you'll have to create your own scheme.  You'd want to take the image as a stream and send it 4KB at a time to reconstruct it on the other end.

**Comment by s1mar** [comment]
I have the same approach in mind but it's the splitting of the byte array into chunks of 4KB and then making sure they reach in order in the other device,this is what's really bugging me,I can figure this out but if you can guide me to some resource or algorithm,that'd be awesome,for I need to present my app in my college fair and the deadline's closing in

**Comment by samtstern** [comment]
Sorry @s1mar this isn't something I've done myself so I don't have any code.  I'd try on StackOverflow for this kind of help.

**Comment by s1mar** [comment]
@samtstern ,Solved it!!took me some while but it wasn't that complicated,thanks .

One thing though,on some devices,I get an error that Google Play Services stopped working etc.It's happening only on some,got any ideas ?
