### ISSUE TITLE
Strategy.DISTANCE_TYPE_EARSHOT does not restrict proximity

### ISSUE THREAD

**Issue by loolooii** [googlesamples/android-nearby#4]
The video on the documentation website claims that EARSHOT distance restricts the message proximity to about 5 feet (1.5 meter), but that is not actually the case.  It even works if the distance is about 10 meters (I haven't tested longer distances). Any comments on this?

**Comment by SilkSama** [comment]
Up

**Comment by brianduff** [comment]
Sorry for delay in response. The distance estimation for EARSHOT is approximate, and is based on the power of both the speaker and the microphone on the sending and receiving devices.
