### ISSUE TITLE
Could not find dependency "com.google.android.gms:play-services-nearby:14.0.0"

### ISSUE THREAD

**Issue by francozappa** [googlesamples/android-nearby#52]
Hi,

I'm not able to import the walkietalkie app. I'm using:

    Android Studio 3.0.1
    Build #AI-171.4443003, built on November 9, 2017
    JRE: 1.8.0_152-release-915-b01 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Linux 4.4.113-1-MANJARO

I'm getting the following error from gradle:

    Could not find dependency "com.google.android.gms:play-services-nearby:14.0.0"

**Comment by samtstern** [comment]
@francozappa apologies that was a mistake in the README.  It should be `11.8.0`.

**Comment by francozappa** [comment]
@samtstern ,

Thanks for the quick response. However if I modify the version I'm getting a different error

    Error:(195, 35) error: cannot find symbol class Builder

**Comment by samtstern** [comment]
@francozappa can you file a new issue and show:

  * The code that leads to that error
  * More of the error
