### ISSUE TITLE
Error:(195, 35) error: cannot find symbol class Builder

### ISSUE THREAD

**Issue by francozappa** [googlesamples/android-nearby#53]
Hi,

I'm trying to Build and Run the walkietalkie app from your repo.

I've changed the dependecy entry to

    compile 'com.google.android.gms:play-services-nearby:11.8.0'

However when I try to build the project I'm getting two errors of this type:

    error: cannot find symbol class Builder

Given by the following two lines of code:

    new AdvertisingOptions.Builder().setStrategy(getStrategy()).build())
    new DiscoveryOptions.Builder().setStrategy(getStrategy()).build())

I'm using

    Android Studio 3.0.1
    Build #AI-171.4443003, built on November 9, 2017
    JRE: 1.8.0_152-release-915-b01 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Linux 4.4.113-1-MANJARO

**Comment by samtstern** [comment]
Fixed this by pull request #54 thanks for catching it.
