### ISSUE TITLE
Fetch Eddystone UID using Nearby Messages API

### ISSUE THREAD

**Issue by akshay0297** [googlesamples/android-nearby#61]
Is there a provision in Nearby Messages API to get the beacon's details like if the Beacon is configured on Eddystone UID is it possible to fetch it's Namespace and Instance ID or UUID, Major and Minor in the case of  registered IBeacon.

**Comment by helenclarko** [comment]
Okay, so... Here is what I would do.
The information on the page below should point you in the right place:

https://developers.google.com/beacons/proximity/reference/rest/v1beta1/beacons/list

This allows you to search the beacons registered to your Google project. 
Using a GET call on the "list" command will return a few things, of which the "Beacon" object is one of them:

https://developers.google.com/beacons/proximity/reference/rest/v1beta1/beacons#Beacon

This will give you the BeaconName which can be used to lookup and change that beacons attachment, activate and deactivate the beacon, decommission it and remove the beacon altogether.

You cannot search based on attachment URL or description, only on the description used to store the beacon with the Google beacon dashboard/platform.
Attachments can only be changed if you have the BeaconName.

-helenclarko

**Comment by akshay0297** [comment]
@helenclarko   Thank You for your reply. I will implement this.
