### ISSUE TITLE
API 28 and androidx: RockPaperScissors build fails with "Program type already present"

### ISSUE THREAD

**Issue by carlrobert-sonymobile** [googlesamples/android-nearby#62]
I can't seem to get Android Nearby Connections to build on API 28 in my project.
At first, I thought it was my project only but it turns out RockPaperScissors is broken in the same way and I suspect it's related to dependencies from the GMS libs.

Building the debug APK, the ':app:transformDexArchiveWithExternalLibsDexMergerForRelease' task always fails with a message such as 
Error: Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

Exactly which "Program type" is reported may vary. The release APK build also fails.

Please refer to the gist (patch) below. I'm running Android Studio 3.2 Beta 2
https://gist.github.com/carlrobert-sonymobile/f8fb438185727633b8e73d61a1de0cf3

**Comment by znakeeye** [comment]
Did you solve this? I'm facing the exact same problem in another project.

**Comment by carlrobert-sonymobile** [comment]
Hi znakeeye and thanks for reminding :)

So, I just made a new attempt and now I can get it to build. Caveat: I have not tried running it yet.

The gist (patch) has been updated. Please report back if this helps.

I used Android Studio 3.2.

Best regards,
Robert

**Comment by carlrobert-sonymobile** [comment]
Resolved by https://github.com/googlesamples/android-nearby/commit/456d88dac9f929d80a0f527b6e100d348b498bcc
