### ISSUE TITLE
Error:Flavor 'automatic' has no flavor dimension.

### ISSUE THREAD

**Issue by Mateeen** [googlesamples/android-nearby#63]

**Comment by brianduff** [comment]
Can you provide more details about the steps you're taking when you see this?

**Comment by funwarioisii** [comment]
I have the same problem.

1. `git clone https://github.com/googlesamples/android-nearby.git`
2. In Android Studio, open `android-nearby/connections/walkietolkie` as a project
3. Sync Project with Gradle Files
4. get this error, `Error:Flavor 'automatic' has no flavor dimension.`



Android Studio 3.3 Beta 4
Build #AI-182.4892.20.33.5114240, built on November 7, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

**Comment by brianduff** [comment]
Fixed in https://github.com/googlesamples/android-nearby/commit/168ad18cbdb50a3cb14fb297b0a8919248e21bb3
