### ISSUE TITLE
Unnecessary semi-colon in progress updates section on API doc page

### ISSUE THREAD

**Issue by knjk04** [googlesamples/android-nearby#71]
I don't know if this is the right place to post this, but if not, please let me know who I need to direct this towards.

On the [Nearby connections API page in the exchange data section](https://developers.google.com/nearby/connections/android/exchange-data) in the progress updates section, I think there is a mistake in the code sample (buildNotification method).

``` java
  NotificationCompat.Builder notification = new NotificationCompat.Builder(this);
      .setContentTitle(isIncoming ? "Receiving..." : "Sending...");
```

I don't think there should be a semi-colon at the end of the first line in the code snippet above. When included, it raises an error ("_cannot resolve method 'setContentTitle(java.lang.String)_'"). Without, it's fine (and I think that's the usual way of working with Builders).

**Comment by brianduff** [comment]
Thanks for reporting, I'm working on updating the documentation, should be fixed in the next couple of days.

**Comment by brianduff** [comment]
Fixed at https://developers.google.com/nearby/connections/android/exchange-data
