### ISSUE TITLE
No getSize() on Payload object?

### ISSUE THREAD

**Issue by knjk04** [googlesamples/android-nearby#72]
In the [exchange data Connections API doc page](https://developers.google.com/nearby/connections/android/exchange-data),  getSize() is being called on a payload object (last line in the code snippet below) in buildNotification().

```java
private NotificationCompat.Builder buildNotification(Payload payload, boolean isIncoming) {
  NotificationCompat.Builder notification = new NotificationCompat.Builder(this);
      .setContentTitle(isIncoming ? "Receiving..." : "Sending...");
  int size = payload.getSize();
```

However, Android Studio is telling me that there isn't such a method (I do have the Payload, PayloadCallback and PayloadTransferUpdate imports). I couldn't find getSize() being used in any of the samples on this repository, so I was wondering whether it (still?) exists?  

If it does exist and I am doing something wrong, I'd like to suggest that a code sample be made that closer resembles the documentation boilerplate code.

**Comment by brianduff** [comment]
Thanks for reporting this, you're right that getSize() doesn't exist. The correct way to get the size of a (non stream) payload is to use the getTotalBytes() method on the PayloadTransferUpdate object passed into PayloadCallback.onPayloadTransferUpdate().

There are actually a few other errors in this sample code.  I'm working on publishing an update to the documentation, should be up hopefully within the next couple of days.

**Comment by brianduff** [comment]
Fixed at https://developers.google.com/nearby/connections/android/exchange-data
