### ISSUE TITLE
Buttons does not fit in the approval dialog

### ISSUE THREAD

**Issue by viplezer** [googlesamples/android-nearby#8]
We recently integrated the new Nearby Messages API into our app and noticed that the approval dialog's buttons does not fit in the approval dialog when we use the application in hungarian language. I attached some screenshots about the bug, this is what we see when we use the app in english:
![english](https://cloud.githubusercontent.com/assets/2778196/10508175/a191b5ba-7325-11e5-8d12-63d73682e011.png)
And this is the hungarian version:
![hungarian](https://cloud.githubusercontent.com/assets/2778196/10508174/a18eb324-7325-11e5-8cfc-eb9278d1cd14.png)

As you can see the Allow button is missing from the dialog.

**Comment by samtstern** [comment]
Thanks for the report!  That's a good find.

@shailen could you file a bug about this?

**Comment by shailen** [comment]
This is a known issue and the eng team is working to fix it. I'll update this space when a fix is ready.

**Comment by ofalvai** [comment]
I can confirm that this is solved now.

Hungarian dialog with Play Services 10.0.84:
![screenshot_2016-11-27-22-53-01](https://cloud.githubusercontent.com/assets/1694986/20652251/18fefbb8-b4f6-11e6-8c96-e0fb459c886e.jpeg)
